### ISSUE TITLE
[NcSelect] Minor presentation issue

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#4943]
When opening NcSelect, there is a small gap between the input and the suggestion box.
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/6266aeb5-fb5e-499b-8a71-28ce85be1df4)

When zooming the page (here 170% with Firefox 121) , the suggestion box gets zoomed different from the other elements
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/251cda29-e6b9-4f31-a67f-b75dd3afb919)

**Comment by dartcafe** [comment]
@Pytal I would like to reopen this issue, since the resizing behavior still exists in 8.5.0.

**Comment by ShGKme** [comment]
> @Pytal I would like to reopen this issue, since the resizing behavior still exists in 8.5.0.

Do you have an example, where it is still broken?

**Comment by dartcafe** [comment]
See the second screenshot. Had it on Firefox and Chrome as well. 
In this case it was the polls app.

**Comment by ShGKme** [comment]
> See the second screenshot. Had it on Firefox and Chrome as well. In this case it was the polls app. But in the files app, this happens too.

What version? Does this version includes the PR with the fix?

**Comment by dartcafe** [comment]
8.5.0

https://github.com/nextcloud-libraries/nextcloud-vue/issues/4943#issuecomment-1907925734

**Comment by dartcafe** [comment]
I see this issue with the lowest priority, since it is an edge case; NcSelect must have the open state while zooming. But the issue should be reopened until fixed. At least the files app is also affected and maybe other apps.

And to clarify before more questions: 
* It still happens with release 8.5.0 as well as with the predecessor.
* Yes, #5095 is included as long - as I assume, because the gap is gone and it is included within the release notes - the fix is checked in with release 8.5.0.

**Comment by dartcafe** [comment]
@Pytal Additional observation [see](https://nextcloud-vue-components.netlify.app/#/Components/NcSelect?id=ncselect-1)

## Initial state
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/fb3aee2b-2b9b-4d34-bdf1-e74c23621c16)


## When selecting a tag
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/93c6a799-0212-49a2-be0a-3711283e4244)

**Comment by ShGKme** [comment]
1/2 issues of the issue was fixed by linked PR

**Comment by ShGKme** [comment]
The issue comes from external library - VueSelect. In `append-to-body` directive it takes the size only on inserted. So changing select size after open results in different size between select's dropdown and select's content.

https://github.com/sagalbot/vue-select/blob/master/src/directives/appendToBody.js

As @Pytal mentioned, some cases it is fixable via disabling `appendToBody`. Comes from https://github.com/nextcloud-libraries/nextcloud-vue/pull/3656

The problem is that without `appendToBody` we have another 2 issues:
1. No auto position (e.g. it opens down when there is no place there)
2. `overflow` viewbox, where Select is cut by container border

**Comment by ShGKme** [comment]
Hmm, a problem might be simpler that it seemed to be. Wait a second...

**Comment by ShGKme** [comment]
@dartcafe please, have a look on the PR above

**Comment by dartcafe** [comment]
Tested with the new release. For the main purpose it works now. Still get a glitch in an absolute edge case.
